name = "SimpleSDMLayers"
uuid = "2c645270-77db-11e9-22c3-0f302a89c64c"
authors = ["Timoth√©e Poisot <timothee.poisot@umontreal.ca>"]
version = "0.1.0"

[deps]
GDAL = "add2ef01-049f-52c4-9ee2-e494f65e021a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
