name = "SimpleSDMLayers"
uuid = "2c645270-77db-11e9-22c3-0f302a89c64c"
authors = ["Timoth√©e Poisot <timothee.poisot@umontreal.ca>"]
version = "0.0.1"

[deps]
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
GDAL = "add2ef01-049f-52c4-9ee2-e494f65e021a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
julia = "1.2"
